# Generated by Django 3.2.6 on 2021-08-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashier',
            old_name='end_hour',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='cashier',
            old_name='start_hour',
            new_name='start_time',
        ),
    ]
